name: Node CI with NPM

on:
  push:
  pull_request:

jobs:
  test-ci:
    runs-on: ubuntu-latest
    env:
      MONGO_URL_DEV: ${{ secrets.MONGO_URL_DEV }}
      EMAIL_HOST_DEV: ${{ secrets.EMAIL_HOST_DEV }}
      EMAIL_PORT_DEV: ${{ secrets.EMAIL_PORT_DEV }}
      EMAIL_USER_DEV: ${{ secrets.EMAIL_USER_DEV }}
      EMAIL_PASSWORD_DEV: ${{ secrets.EMAIL_PASSWORD_DEV }}

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test:coverage
