name: Node CI with NPM

on:
  push:
  pull_request:

jobs:
  test-ci:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Start docker container
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Create env file
        run: |
          touch .env
          echo EMAIL_HOST_DEV=${{secrets.EMAIL_HOST_DEV}} >> .env
          echo EMAIL_PASSWORD_DEV=${{secrets.EMAIL_PASSWORD_DEV}} >> .env
          echo EMAIL_PORT_DEV=${{secrets.EMAIL_PORT_DEV}} >> .env
          echo EMAIL_USER_DEV=${{secrets.EMAIL_USER_DEV}} >> .env
          echo MONGO_URL_DEV=${{secrets.MONGO_URL_DEV}} >> .env

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test:coverage

      - name: Stop container
        if: always()
        run: docker-compose -f "docker-compose.yml" down
