name: Node CI with NPM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set NodeJs 18v
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          run:
        env:
          MONGO_URL_DEV: ${{ secrets.DB_URL }}
      - run: npm ci
      - run: npm run test:coverage
