name: Node CI with NPM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          touch .env
          echo 'MONGO_URL_DEV=${{ secrets.DB_URL }}' >> .env
          cat .env
      - name: Set NodeJs 18v
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run test:coverage
